### PR TITLE
Remove userInfo update for watch complication data

### PR DESCRIPTION
**Pull request by rodericj**
Given the complexity (har) of the issue we decided to
punt this feature for now. The size of the data
and the limitations of the platform require
a larger strategy.

### CODE REVIEW

**Comment by rodericj** [comment]
@someoneAnyone, let me know if there is more stuff that needs to get removed around this feature. I did my best to find the related code.

**Comment by someoneAnyone** [comment]
I'll test it today! Thank you.

**Comment by someoneAnyone** [comment]
@rodericj i'm not seeing it update the watch. did it work for you?

**Comment by rodericj** [comment]
No the updates don't work. This simply removed the effort to set the `userInfo` dictionary which was not working at all. This was more of a cleanup task than anything else.

**Pull request closed without merging**
